app/compare/urls.py
from django.urls import path, include

from . import views

app_name = 'compare'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path('activity/<int:pk>', views.ActivityDetailView.as_view(), name='activity-detail'),
    path('activity/<int:pk>/data', views.json_ride, name='activity-data'),
    path("activity/data", views.json_rides, name="activities-data"), # expects query parameters for 'activities'
    path("group/data/<int:pk>", views.group_rides, name="group-data"), # expects query parameters for 'activities'
    path('activity/compare', views.compareView, name='compare'), # expects query parameters for 'activities'
    path('activity/group', views.set_group, name='group'),
    path('groups', views.GroupView.as_view(), name='grouplist'),
    path('groups/<int:pk>', views.compareView, name='group-compare'),
    path("upload", views.upload_file, name="upload"),
    path('accounts/signup', views.signup, name='signup'),
]

app/fit_compare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('compare.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
{% extends 'base_generic.html' %}

{% block base %}

<div class="section">
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
</div>

{% endblock base %}

app/templates/base_generic.html
<head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
  <title>
    {% block title %}
    Fit Compare
    {% endblock title %}
  </title>
  {% block header %}
  {% endblock header %}
</head>

<body>
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a href="{% url 'compare:index' %}" class="navbar-item is-size-2 has-text-white">Fit Compare</a>
      <!-- <a class="navbar-item" href="https://bulma.io">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
      </a> -->
      <a href="{% url 'compare:grouplist' %}" class="navbar-item is-size-5">Groups</a>
      <a href="{% url 'compare:index' %}" class="navbar-item is-size-5">Activities</a>
      
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
      data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'compare:index' %}">
          Home
        </a>

      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if user.is_authenticated %}
            <a class="button is-light" href="{% url 'logout' %}">
              Log Out
            </a>
            {% else %}
            <a class="button is-primary" href="{% url 'compare:signup' %}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{% url 'login' %}">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

      {% block base %}
      {% endblock %}

      {% block scripts %}
      {% endblock scripts %}
</body>

app/templates/form_generic.html
{% extends "base_generic.html" %}

{% block base %}

<section class="hero is-primary is-fullheight-with-navbar">
    <div class="hero-body">
      <div class="container">
          
          <div class="card">
              <div class="card-content">
                  {% block form %}
                  
                  {% endblock form %}
              </div>
          </div>
        
      </div>
    </div>
  </section>

  
{% endblock %}

app/templates/form_snippet.html
{% for field in form %}
<div class="field">
  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
  <div class="control">
    <input type="{{ field.field.widget.input_type }}" class="input" name="{{ field.html_name }}" multiple>
  </div>
  <p class="help">{{ field.help_text }}</p>
</div>        
{% endfor %}

app/templates/item_detail.html
{% extends 'base.html' %}

{% block title %}
Item Detail
{% endblock title %}

{% block content %}

{% if item %}

<article class="media box">
    <figure class="media-left">
        <p class="image is-128x128">
            <img src="{{ item.img_url }}" alt="product image">
        </p>
    </figure>
    <div class="media-content">
        <div class="content">
            <h2 class="is-size-3">{{ item.item_name }}</h2>
            <p><strong>Item Number: </strong><a href="https://www.aliexpress.com/item/{{ item.item_number }}.html" target="_blank">{{ item.item_number }}</a></p>
            <p><strong>Added: </strong>{{ item.created_date }}</p>
        </div>
    </div>
</article>

<div class="tile is-8">
    <div id="chart"></div>
    <canvas id="myChart" width="700" height="400"></canvas>
    {% else %}
    <p>This item number does not exist.</p>
</div>
{% endif %}

{{ prices|json_script:"data" }}

<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.15/c3.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.16.0/d3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.15/c3.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>


<script>
    const itemId = document.location.pathname.split('/').pop()
    var timeFormat = 'MM/DD/YYYY HH:mm';
    fetch(`/item/${itemId}/prices`)
        .then(response => response.json())
        .then(json => {
            let chartData = json.map(c => {
                return {
                    t: new Date(c.datetime),
                    y: c.price
                }
            })
            console.log(chartData)
            const ctx = document.getElementById('myChart').getContext('2d')
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    datasets: [
                        {
                            label: 'Product Price',
                            stepped: 'before',
                            data: chartData,
                        }
                    ]
                },
                options: {
                    scales: {
                        yAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: 'Price'
                            }
                            // ticks: {
                            //     beginAtZero: true
                            // }
                        }],
                        xAxes: [{
                            type: 'time',
                            distribution: 'series',
                            time: {
                                parser: timeFormat,
                                tooltipFormat: 'll HH:mm'   
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Date'
                            }
                        }]
                    },
                    tooltips: {
                        mode: 'x',
                        intersect: false,
                    }
                }
            });
            console.log(json)
        })
    // let data = JSON.parse(document.getElementById('data').textContent)
    // let col = ['price']
    // // let x = ['x']
    // data.map(c => {
    //     col.push(parseFloat(c.price))
    //     // x.push(c.datetime)
    // })
    // // console.log(x, col)
    // var chart = c3.generate({
    //     bindto: '#chart',
    //     data: {
    //         columns: [
    //             col,
    //         ]
    //     },
    // });
    // document.getElementById('text').textContent = JSON.stringify(data)
</script>

{% endblock content %}