app/compare/urls.py
from django.urls import path, include

from . import views

app_name = 'compare'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path('activity/<int:pk>', views.ActivityDetailView.as_view(), name='activity-detail'),
    path('activity/<int:pk>/data', views.json_ride, name='activity-data'),
    path("activity/data", views.json_rides, name="activities-data"), # expects query parameters for 'activities'
    path("group/data/<int:pk>", views.group_rides, name="group-data"), # expects query parameters for 'activities'
    path('activity/compare', views.compareView, name='compare'), # expects query parameters for 'activities'
    path('activity/group', views.set_group, name='group'),
    path('groups', views.GroupView.as_view(), name='grouplist'),
    path('groups/<int:pk>', views.compareView, name='group-compare'),
    path("upload", views.upload_file, name="upload"),
    path('accounts/signup', views.signup, name='signup'),
]

app/fit_compare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('compare.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/compare/models.py
from django.db import models

# Create your models here.
class RideFile(models.Model):
    file = models.FileField(upload_to='activities/%Y/%m/%d')

class Activity(models.Model):
    fitfile = models.OneToOneField(RideFile, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=20)
    timestamp = models.DateTimeField()
    start_time = models.DateTimeField()
    start_position_lat = models.FloatField(default=None, blank=True, null=True)
    start_position_long = models.FloatField(default=None, blank=True, null=True)
    total_elapsed_time = models.FloatField(default=None, blank=True, null=True)
    total_timer_time = models.FloatField(default=None, blank=True, null=True)
    total_distance = models.FloatField(default=None, blank=True, null=True)
    total_cycles = models.IntegerField(default=None, blank=True, null=True)
    total_work = models.IntegerField(default=None, blank=True, null=True)
    enhanced_avg_speed = models.IntegerField(default=None, blank=True, null=True)
    enhanced_max_speed = models.IntegerField(default=None, blank=True, null=True)
    enhanced_avg_altitude = models.IntegerField(default=None, blank=True, null=True)
    enhanced_min_altitude = models.IntegerField(default=None, blank=True, null=True)
    enhanced_max_altitude = models.IntegerField(default=None, blank=True, null=True)
    total_calories = models.IntegerField(default=None, blank=True, null=True)
    avg_speed = models.IntegerField(default=None, blank=True, null=True)
    max_speed = models.IntegerField(default=None, blank=True, null=True)
    avg_power = models.IntegerField(default=None, blank=True, null=True)
    max_power = models.IntegerField(default=None, blank=True, null=True)
    total_ascent = models.IntegerField(default=None, blank=True, null=True)
    total_descent = models.IntegerField(default=None, blank=True, null=True)
    num_laps = models.IntegerField(default=None, blank=True, null=True)
    normalized_power = models.IntegerField(default=None, blank=True, null=True)
    training_stress_score = models.FloatField(default=None, blank=True, null=True)
    intensity_factor = models.FloatField(default=None, blank=True, null=True)
    threshold_power = models.IntegerField(default=None, blank=True, null=True)
    event = models.CharField(max_length=10, default=None, blank=True, null=True)
    event_type = models.CharField(max_length=10, default=None, blank=True, null=True)
    sport = models.CharField(max_length=20, default=None, blank=True, null=True)
    sub_sport = models.CharField(max_length=10, default=None, blank=True, null=True)
    avg_heart_rate = models.IntegerField(default=None, blank=True, null=True)
    max_heart_rate = models.IntegerField(default=None, blank=True, null=True)
    avg_cadence = models.IntegerField(default=None, blank=True, null=True)
    max_cadence = models.IntegerField(default=None, blank=True, null=True)
    total_training_effect = models.FloatField(default=None, blank=True, null=True)
    avg_temperature = models.IntegerField(default=None, blank=True, null=True)
    max_temperature = models.IntegerField(default=None, blank=True, null=True)
    avg_fractional_cadence = models.FloatField(default=None, blank=True, null=True)
    max_fractional_cadence = models.FloatField(default=None, blank=True, null=True)
    total_fractional_cycles = models.FloatField(default=None, blank=True, null=True)
    total_anaerobic_training_effect = models.FloatField(default=None, blank=True, null=True)
    # nec_lat = models.FloatField(default=None, blank=True, null=True)
    # nec_long = models.FloatField(default=None, blank=True, null=True)
    # swc_lat = models.FloatField(default=None, blank=True, null=True)
    # swc_long = models.FloatField(default=None, blank=True, null=True)
    # avg_stroke_count = models.IntegerField(default=None, blank=True, null=True)
    # time_standing = models.IntegerField(default=None, blank=True, null=True)
    # message_index = models.IntegerField(default=None, blank=True, null=True)
    # first_lap_index = models.IntegerField(default=None, blank=True, null=True)
    # left_right_balance = models.IntegerField(default=None, blank=True, null=True)
    # avg_stroke_distance = models.IntegerField(default=None, blank=True, null=True)
    # pool_length = models.IntegerField(default=None, blank=True, null=True)
    # num_active_lengths = models.IntegerField(default=None, blank=True, null=True)
    # avg_vertical_oscillation = models.IntegerField(default=None, blank=True, null=True)
    # avg_stance_time_percent = models.IntegerField(default=None, blank=True, null=True)
    # avg_stance_time = models.IntegerField(default=None, blank=True, null=True)
    # stand_count = models.IntegerField(default=None, blank=True, null=True)
    # avg_vertical_ratio = models.IntegerField(default=None, blank=True, null=True)
    # avg_stance_time_balance = models.IntegerField(default=None, blank=True, null=True)
    # avg_step_length = models.IntegerField(default=None, blank=True, null=True)
    # event_group = models.IntegerField(default=None, blank=True, null=True)
    # trigger = models.CharField(max_length=20, default=None, blank=True, null=True)
    # swim_stroke = models.IntegerField(default=None, blank=True, null=True)
    # pool_length_unit = models.IntegerField(default=None, blank=True, null=True)
    # avg_left_torque_effectiveness = models.IntegerField(default=None, blank=True, null=True)
    # avg_right_torque_effectiveness = models.IntegerField(default=None, blank=True, null=True)
    # avg_left_pedal_smoothness = models.IntegerField(default=None, blank=True, null=True)
    # avg_right_pedal_smoothness = models.IntegerField(default=None, blank=True, null=True)
    # avg_combined_pedal_smoothness = models.IntegerField(default=None, blank=True, null=True)
    # avg_left_pco = models.IntegerField(default=None, blank=True, null=True)
    # avg_right_pco = models.IntegerField(default=None, blank=True, null=True)
    # avg_cadence_position = models.IntegerField(default=None, blank=True, null=True)
    # max_cadence_position = models.IntegerField(default=None, blank=True, null=True)


class Device(models.Model):
    serial_number = models.CharField(max_length=20)
    manufacturer = models.CharField(max_length=30)
    garmin_product = models.CharField(max_length=30)

class Record(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    timestamp = models.DateTimeField()
    position_lat = models.FloatField(default=None, blank=True, null=True)
    position_long = models.FloatField(default=None, blank=True, null=True)
    distance = models.FloatField(default=None, blank=True, null=True)
    accumulated_power = models.IntegerField(default=None, blank=True, null=True)
    speed = models.FloatField(default=None, blank=True, null=True)
    altitude = models.FloatField(default=None, blank=True, null=True)
    power = models.IntegerField(default=None, blank=True, null=True)
    heart_rate = models.IntegerField(default=None, blank=True, null=True)
    cadence = models.IntegerField(default=None, blank=True, null=True)
    temperature = models.IntegerField(default=None, blank=True, null=True)

class ActivityGroup(models.Model):
    activity = models.ManyToManyField(Activity)
    name = models.CharField(max_length=50)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

app/compare/forms.py
from django import forms
from multiupload.fields import MultiFileField

class UploadFileForm(forms.Form):
    files = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label = 'Upload your ride files.',
        help_text='Max 42 MB',
        # min_num=1,
        # max_num=10,
        # max_file_size=1024*1024*42
    )

app/compare/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect, JsonResponse
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
from django.utils import timezone
from .fitprocessing import handle_uploaded_file
from .forms import UploadFileForm
from .models import Activity, ActivityGroup

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')
        if form.is_valid():
            for f in files:
                handle_uploaded_file(f)
            return HttpResponseRedirect(reverse('compare:upload'))
    else:
        form = UploadFileForm()
    return render(request, 'upload_new.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('compare:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

def json_ride(request, pk):
    records = Activity.objects.get(id=pk).record_set.all().values()
    return JsonResponse(list(records), safe=False)

def json_rides(request):
    activities = request.GET.get('activities', None)
    acts = []
    if activities:
        for act in activities.split(','):
            acts.append(list(Activity.objects.get(id=act).record_set.all().values()))
    return JsonResponse(acts, safe=False)

def group_rides(request, pk):
    activities = list(ActivityGroup.objects.get(id=pk).activity.all().values_list('id', flat=True))
    acts = []
    if activities:
        for act in activities:
            acts.append(list(Activity.objects.get(id=act).record_set.all().values()))
    return JsonResponse(acts, safe=False)

def set_group(request):
    if request.method == 'POST':
        activities = list(request.POST.keys())
        activities = activities[1:len(activities)-1]
        name = request.POST['name']
        group = ActivityGroup(name=name)
        group.save()
        group.activity.add(*activities)
        # for act in activities:
        #     group.acti.add(act)
        # print(request)
    return HttpResponseRedirect(reverse('compare:index'))


class IndexView(generic.ListView):
    template_name = 'index.html'
    model = Activity

class ActivityDetailView(generic.DetailView):
    template_name = 'activity_detail_uplot.html'
    model = Activity

class GroupView(generic.ListView):
    template_name = 'groups.html'
    model = ActivityGroup

def compareView(request, pk):
    # activities = request.GET.get('activities', None)
    group = ActivityGroup.objects.get(id=pk)
    activities = list(group.activity.all().values_list('id', flat=True))
    # if activities:
    #     activities = activities.split(',')

    return render(request, 'compare.html', {"activities": activities, "group": group})

app/compare/templates/activity_detail.html
{% extends 'base.html' %}

{% block header %}

{% load static %}
<link href="{% static 'css/c3.min.css' %}" rel="stylesheet">

{% endblock header %}

{% block content %}

<div id="chart"></div>

{% endblock content %}

{% block scripts %}

<script src="{% static 'js/d3.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/c3.js' %}"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.14/c3.min.js" integrity="sha256-MnAgiFGk5ixLKB7CFst+gMpO34QSStl8aLQt85SQKcY=" crossorigin="anonymous"></script> -->
<script>
//   var chart = c3.generate({
//     bindto: '#chart',
//     data: {
//       columns: [
//         ['data1', 30, 200, 100, 400, 150, 250],
//         ['data2', 50, 20, 10, 40, 15, 25]
//       ]
//     }
// });

const actId = document.location.pathname.split('/').pop()
fetch(`/activity/${actId}/data`)
  .then(response => response.json())
  .then(json => {
    el = document.getElementById('chart')
    // console.log(json)
    chart = c3.generate({
      bindto: '#chart',
      data: {
        json: json.filter((d,i) => (i+1)%5 == 0),
        keys: {
          // x: 'timestamp',
          value: ['speed', 'altitude']
        },
        type: 'spline',
      },
      axis: {
        x: {
          type: 'category',
          tick: {
            culling: {
              max: 10
            },
            count: 10,
            // rotate: 45, 
            // format: '%H:%M'
          },
          label: 'Time',
        }
      },
      // zoom: {enabled: true},
      // subchart: {show: true},
      point: {show: false}, // remove markers
    })
  })
</script>

{% endblock scripts %}

app/compare/templates/activity_detail_uplot.html
{% extends 'base.html' %}

{% block header %}

{% load static %}
<link href="{% static 'css/uPlot.css' %}" rel="stylesheet">

{% endblock header %}

{% block content %}

<div class="select is-multiple is-loading">
  <select name="plots[]" id="plots-select" multiple>

  </select>
</div>
<div id="chart"></div>

{% endblock content %}

{% block scripts %}

<script src="{% static 'js/uPlot.iife.js' %}" charset="utf-8"></script>

<script>
  function prepData(packed) {
    console.time("prep");
    let keys = Object.keys(packed[0]).slice(5)

    let data = []
    for (let i = 0; i <= keys.length; i++)
      data.push(Array(packed.length))

    for (let i = 0; i < packed.length; i++) {
      data[0][i] = new Date(packed[i].timestamp).getTime() / 1000
      Object.values(packed[i]).slice(5).map((c, j) => {
        data[j + 1][i] = c
      })
    }

    console.timeEnd("prep");

    return data;
  }

  let dataProps = {
    distance: {
      key: 'distance',
      scale: 'm',
      stroke: 'sienna',
      fill: "",
    },
    accumulated_power: {
      key: 'accumulated_power',
      scale: 'J',
      stroke: 'blue',
      fill: null,
    },
    speed: {
      key: 'speed',
      scale: 'mph',
      stroke: 'blue',
      fill: '',
    },
    altitude: {
      key: 'altitude',
      scale: 'm',
      stroke: 'sienna',
      fill: "rgb(160,82,45,0.1)",
    },
    power: {
      key: 'power',
      scale: 'W',
      stroke: 'green',
      fill: '',
    },
    heart_rate: {
      key: 'heart_rate',
      scale: 'bpm',
      stroke: 'orange',
      fill: '',
    },
    cadence: {
      key: 'cadence',
      scale: 'm',
      stroke: 'purple',
      fill: '',
    },
    temperature: {
      key: 'temperature',
      scale: 'C',
      stroke: 'green',
      fill: '',
    },
  }

  let makeSeries = function ({
    key,
    scale,
    stroke = 'blue',
    fill = null
  }) {
    return {
      series: {
        label: key.charAt(0).toUpperCase() + key.slice(1),
        scale: scale,
        value: (u, v) => v == null ? '-' : v.toFixed() + scale,
        stroke: stroke,
        fill: fill ? fill : null,
        width: 1 / devicePixelRatio,
      },
      axes: {
        // side: 0,
        scale: scale,
        size: 100,
        values: (u, vals, space) => vals.map(v => +v.toFixed(2) + ' ' + scale),
        // grid: {show: false},
      }
    }
  }

  function makeChart(data, key = 'power') {
    console.time("chart");
    const series = makeSeries(dataProps[key])
    const cursorOpts = {
      lock: true,
      sync: {
        key: 'Mooooo',
        setSeries: true,
      },
      x: true,
      y: false,
    }
    const opts = {
      // title: "Test",
      width: 800,
      height: 200,
      cursor: cursorOpts,
      series: [{},
        series.series,
      ],
      axes: [{},
        series.axes,
      ],
    };
    let el = document.getElementById('chart')
    let uplot = new uPlot(opts, data, el);

    // wait.textContent = "Done!";
    console.timeEnd("chart");
    return uplot
  }

  function getSelectedOptions(sel, fn) {
    var opts = [],
      opt;
    for (var i = 0, len = sel.options.length; i < len; i++) {
      opt = sel.options[i];
      if (opt.selected) {
        opts.push(opt.value);
        if (fn) {
          fn(opt);
        }
      }
    }
    return opts;
  }

  // let wait = document.getElementById("wait");
  const actId = document.location.pathname.split('/').pop()
  let plots = {}
  const select = document.getElementById('plots-select')
  fetch(`/activity/${actId}/data`).then(r => r.json()).then(packed => {
    // wait.textContent = "Rendering...";
    console.time('ready')
    console.log(Object.keys(packed[0]).slice(5))
    let data = prepData(packed);
    setTimeout(() => {
      Object.keys(packed[0])
        .slice(5)
        .map((c, i) => {
          plots[c] = makeChart(Array(data[0], data[i + 1]), c)
        })
    }, 0);
    
    Object.keys(packed[0]).slice(5).map(c => {
      select.add(new Option(c, c, true, true))
    })

    setTimeout(() => console.timeEnd('ready'), 0)
  });

  select.onchange = function (e) {
    let selected = getSelectedOptions(select)
    // console.log(selected)
    for (key of Object.keys(plots)) {
      plots[key].root.hidden = selected.includes(key) ? false : true
    }
  }
</script>

{% endblock scripts %}

app/compare/templates/compare.html
{% extends 'base.html' %}

{% block header %}

{% load static %}
<link href="{% static 'css/uPlot.css' %}" rel="stylesheet">

{% endblock header %}

{% block content %}

{% if activities %}
<div class="is-loading"></div>
{% else %}
<p class="is-size-3">No activities queried</p>
{% endif %}
<div class="columns">
  <div class="column is-one-fifth">
    <div class="select is-multiple">
      <select id="plots-select" multiple>
      </select>
    </div>
  </div>
  <div class="column">
    <progress class="progress is-large is-primary" max="100" id="loader">60%</progress>
    <div id="chart" data-activities="{{ activities }}" data-group="{{ group.id }}"></div>
  </div>
</div>

{% endblock content %}

{% block scripts %}

<script src="{% static 'js/uPlot.iife.js' %}" charset="utf-8"></script>

<script>
  function prepData(packed) {
    console.time("prep");
    const keys = Object.keys(packed[0][0]).slice(5)
    const keyLen = keys.length
    let data = []
    const lengths = packed.map(c => c ? c.length : null)
    const maxLen = packed.reduce((a, c, i) => c.length > a[0] ? [c.length, i] : a, [0, 0])
    for (let i = 0; i <= keys.length * packed.length; i++) {
      data.push(Array(maxLen[0]))
    }
    for (let i = 0; i < maxLen[0]; i++) {
      data[0][i] = new Date(packed[maxLen[1]][i].timestamp).getTime() / 1000
      for (let k = 0; k < packed.length; k++) {
        if (packed[k] && lengths[k] > i) {
          Object.values(packed[k][i]).slice(5).map((c, j) => {
            data[k * keyLen + j + 1][i] = c
          })
        } else {
          keys.map((c, j) => {
            data[k * keyLen + j + 1][i] = null
          })
        }
      }
    }

    console.timeEnd("prep");

    return data;
  }

  let dataProps = {
    distance: {
      key: 'distance',
      scale: 'm',
      stroke: 'hsl(270, 49%, 40%)',
      fill: "",
    },
    accumulated_power: {
      key: 'accumulated_power',
      scale: 'J',
      stroke: 'hsl(135, 49%, 40%)',
      fill: null,
    },
    speed: {
      key: 'speed',
      scale: 'mph',
      stroke: 'hsl(45, 49%, 40%)',
      fill: '',
    },
    altitude: {
      key: 'altitude',
      scale: 'm',
      stroke: 'hsl(270, 49%, 40%)',
      fill: "rgb(180,82,45,0.1)",
    },
    power: {
      key: 'power',
      scale: 'W',
      stroke: 'hsl(90, 49%, 40%)',
      fill: '',
    },
    heart_rate: {
      key: 'heart_rate',
      scale: 'bpm',
      stroke: 'hsl(0, 100%, 40%)',
      fill: '',
    },
    cadence: {
      key: 'cadence',
      scale: 'rpm',
      stroke: 'hsl(225, 49%, 40%)',
      fill: '',
    },
    temperature: {
      key: 'temperature',
      scale: 'C',
      stroke: 'hsl(315, 49%, 40%)',
      fill: '',
    },
  }

  function parseHSL(str) {
    var hsl, h, s, l
    hsl = str.replace(/[^\d,]/g, '').split(',') // strip non digits ('%')  
    h = Number(hsl[0]) // convert to number
    s = Number(hsl[1])
    l = Number(hsl[2])
    return [h, s, l] // return parts
  }

  const rp = 'hsl(270, 49%, 40%)'

  function harmonize(color, start, end, interval) {
    const colors = [color]
    const [h, s, l] = parseHSL(color)

    for (let i = start; i <= end; i += interval) {
      const h1 = (h + i) % 360
      const c1 = `hsl(${h1}, ${s}%, ${l}%)`
      colors.push(c1)
    }

    return colors
  }

  let makeSeries = function ({
    key,
    scale,
    stroke = 'blue',
    fill = null
  }, len = 1) {

    let split = harmonize(stroke, 120, 240, 120)

    series = []
    for (let i = 0; i < len; i++) {
      series.push({
        label: key.charAt(0).toUpperCase() + key.slice(1),
        scale: scale,
        value: (u, v) => v == null ? '-' : v.toFixed() + scale,
        stroke: split[i],
        fill: fill ? fill : null,
        width: 1 / devicePixelRatio,
      })
    }
    return {
      series,
      axes: {
        // side: 0,
        scale: scale,
        size: 100,
        values: (u, vals, space) => vals.map(v => +v.toFixed(2) + ' ' + scale),
        // grid: {show: false},
      }
    }
  }

  function makeChart(data, key = 'power') {
    console.time("chart");
    const series = makeSeries(dataProps[key], data.length - 1)
    // console.log(series)
    const initSize = getSize()
    const cursorOpts = {
      lock: true,
      sync: {
        key: 'Mooooo',
        setSeries: true,
      },
      x: true,
      y: false,
    }
    const opts = {
      // title: "Test",
      width: initSize.width,
      height: initSize.height,
      cursor: cursorOpts,
      series: [{},
        ...series.series,
      ],
      axes: [{},
        series.axes,
        // {},
        // series.axes, // temporary double
      ],
    };
    let el = document.getElementById('chart')
    let uplot = new uPlot(opts, data, el);

    // wait.textContent = "Done!";
    console.timeEnd("chart");
    return uplot
  }

  function getSelectedOptions(sel, fn) {
    var opts = [],
      opt;
    for (var i = 0, len = sel.options.length; i < len; i++) {
      opt = sel.options[i];
      if (opt.selected) {
        opts.push(opt.value);
        if (fn) {
          fn(opt);
        }
      }
    }
    return opts;
  }

  // let wait = document.getElementById("wait");
  const chart = document.getElementById('chart')
  const activities = JSON.parse(chart.dataset.activities)
  const groupId = JSON.parse(chart.dataset.group)
  // const search = document.location.search
  let plots = {}
  const select = document.getElementById('plots-select')
  console.time('fetch')
  fetch(`/group/data/${groupId}`).then(r => r.json()).then(packed => {
    // wait.textContent = "Rendering...";
    console.timeEnd('fetch')
    console.time('ready')
    // console.log(packed)
    // console.log(Object.keys(packed[0][0]).slice(5))
    const keys = Object.keys(packed[0][0]).slice(5)
    let data = prepData(packed);
    // console.log(data)
    setTimeout(() => {
      // console.log(keys)
      keys.map((c, i) => {
        // console.log(c, i)
        let dataArray = Array(packed.length + 1)
        dataArray[0] = data[0]
        for (let j = 1; j <= packed.length; j++) {
          dataArray[j] = data[i + 1 + keys.length * (j - 1)]
        }
        // console.log(dataArray)
        plots[c] = makeChart(dataArray, c)
      })
      document.getElementById('loader').remove()
    }, 0);

    keys.map(c => {
      select.add(new Option(c, c, true, true))
    })
    select.parentElement.classList.remove('is-loading')

    setTimeout(() => console.timeEnd('ready'), 0)
  });

  select.onchange = function (e) {
    let selected = getSelectedOptions(select)
    // console.log(selected)
    for (key of Object.keys(plots)) {
      plots[key].root.hidden = selected.includes(key) ? false : true
    }
  }

  function getSize() {
    const container = document.getElementsByClassName('columns')[0]
    const cols = document.getElementsByClassName('column')
    return {
      width: container.clientWidth - cols[0].clientWidth,
      height: 400,
    }
  }

  function throttle(cb, limit) {
    var wait = false;

    return () => {
      if (!wait) {
        requestAnimationFrame(cb);
        wait = true;
        setTimeout(() => {
          wait = false;
        }, limit);
      }
    }
  }

  window.addEventListener("resize", throttle(() => {
    let size = getSize()
    Object.keys(plots).map(u => plots[u].setSize(size))
  }, 200));
</script>

{% endblock scripts %}

app/compare/templates/groups.html
{% extends 'base.html' %}

{% block content %}

{% if activitygroup_list %}

  <table class="table is-bordered is-hoverable has-text-centered">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      {% for group in activitygroup_list %}
      <tr>
        <td><a href="{% url 'compare:group-compare' group.id %}">{{ group.name }}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endif %}

{% endblock content %}

app/compare/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% if activity_list %}
<form action="{% url 'compare:group' %}" method="post" id="groupform">
  {% csrf_token %}

  <table class="table is-bordered is-hoverable has-text-centered">
    <thead>
      <tr>
        <th></th>
        <th>Activity</th>
        <th>Start Time</th>
        <th>Distance</th>
      </tr>
    </thead>
    <tbody>
      {% for act in activity_list %}
      <tr>
        <td><input id="{{ act.id }}" type="checkbox" value="true" name="{{ act.id }}"></td>
        <td><a href="{% url 'compare:activity-detail' act.id %}">{{ act.fitfile.file.name }}</a></td>
        <td>{{ act.start_time }}</td>
        <td>{{ act.total_distance }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="field">
    <label for="name">Group Name</label>
    <div class="control">
      <input type="text" class="input" name="name">
    </div>
    <p class="help">Please enter the group name</p>
  </div>
  <button type="submit" class="button is-primary">Group Rides</button>
</form>

{% endif %}

{% endblock content %}

{% block scripts %}
<script>
  // const form = document.getElementById('groupform')
  // form.addEventListener('submit', function(e) {
  //   form
  // })
</script>
{% endblock scripts %}

app/compare/templates/upload.html
{% extends 'base.html' %}

{% block content %}

  <form action="{% url 'compare:index' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field">
      <div class="file has-name is-boxed">
        <label class="file-label" for="image_file">
            <input class="file-input" type="file" name="image_file" multiple>
            <span class="file-cta">
                <span class="file-icon">
                    <i class="fa fa-upload"></i>
                </span>
                <span class="file-label">
                    Choose a file…
                </span>
            </span>
            <span class="file-name">Please select a file.</span>
        </label>
      </div>
    </div>
    <div class="field">
      <button type="submit" class="button is-primary">Submit</button>
    </div>
  </form>

  {% if image_url %}
    <p>File uploaded at: <a href="{{ image_url }}" class="is-link">{{ image_url }}</a></p>
  {% endif %}

{% endblock %}

app/compare/templates/upload_new.html
{% extends 'form_generic.html' %}

{% block form %}
<form action="{% url 'compare:upload' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'form_snippet.html' %}
  <button type="submit" class="button is-primary">Submit</button>
</form>
{% endblock form %} 